// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-protos-go-apiv2/peer"
	"github.com/hyperledger/fabric/internal/peer/rest"
)

type InvokeNoShimer struct {
	InvokeNoShimStub        func([][]byte, *peer.SignedProposal, bool) *peer.Response
	invokeNoShimMutex       sync.RWMutex
	invokeNoShimArgsForCall []struct {
		arg1 [][]byte
		arg2 *peer.SignedProposal
		arg3 bool
	}
	invokeNoShimReturns struct {
		result1 *peer.Response
	}
	invokeNoShimReturnsOnCall map[int]struct {
		result1 *peer.Response
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *InvokeNoShimer) InvokeNoShim(arg1 [][]byte, arg2 *peer.SignedProposal, arg3 bool) *peer.Response {
	var arg1Copy [][]byte
	if arg1 != nil {
		arg1Copy = make([][]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.invokeNoShimMutex.Lock()
	ret, specificReturn := fake.invokeNoShimReturnsOnCall[len(fake.invokeNoShimArgsForCall)]
	fake.invokeNoShimArgsForCall = append(fake.invokeNoShimArgsForCall, struct {
		arg1 [][]byte
		arg2 *peer.SignedProposal
		arg3 bool
	}{arg1Copy, arg2, arg3})
	stub := fake.InvokeNoShimStub
	fakeReturns := fake.invokeNoShimReturns
	fake.recordInvocation("InvokeNoShim", []interface{}{arg1Copy, arg2, arg3})
	fake.invokeNoShimMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *InvokeNoShimer) InvokeNoShimCallCount() int {
	fake.invokeNoShimMutex.RLock()
	defer fake.invokeNoShimMutex.RUnlock()
	return len(fake.invokeNoShimArgsForCall)
}

func (fake *InvokeNoShimer) InvokeNoShimCalls(stub func([][]byte, *peer.SignedProposal, bool) *peer.Response) {
	fake.invokeNoShimMutex.Lock()
	defer fake.invokeNoShimMutex.Unlock()
	fake.InvokeNoShimStub = stub
}

func (fake *InvokeNoShimer) InvokeNoShimArgsForCall(i int) ([][]byte, *peer.SignedProposal, bool) {
	fake.invokeNoShimMutex.RLock()
	defer fake.invokeNoShimMutex.RUnlock()
	argsForCall := fake.invokeNoShimArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *InvokeNoShimer) InvokeNoShimReturns(result1 *peer.Response) {
	fake.invokeNoShimMutex.Lock()
	defer fake.invokeNoShimMutex.Unlock()
	fake.InvokeNoShimStub = nil
	fake.invokeNoShimReturns = struct {
		result1 *peer.Response
	}{result1}
}

func (fake *InvokeNoShimer) InvokeNoShimReturnsOnCall(i int, result1 *peer.Response) {
	fake.invokeNoShimMutex.Lock()
	defer fake.invokeNoShimMutex.Unlock()
	fake.InvokeNoShimStub = nil
	if fake.invokeNoShimReturnsOnCall == nil {
		fake.invokeNoShimReturnsOnCall = make(map[int]struct {
			result1 *peer.Response
		})
	}
	fake.invokeNoShimReturnsOnCall[i] = struct {
		result1 *peer.Response
	}{result1}
}

func (fake *InvokeNoShimer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *InvokeNoShimer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ rest.InvokeNoShimer = new(InvokeNoShimer)
