# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags: [ v2.* ]

env:
  GO_VER: 1.18.10

permissions:
  contents: read

jobs:
  build-binaries:
    name: Build Fabric Binaries
    strategy:
      matrix:
        include:
        - image: ubuntu-20.04
          target: linux
          arch: amd64
        - image: macos-11
          target: darwin
          arch: amd64
        - image: windows-2022
          target: windows
          arch: amd64
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VER }}
      - name: Checkout Fabric Code
        uses: actions/checkout@v3
      - name: Set three digit RELEASE (strip leading v)
        run: echo "RELEASE=$(echo ${{ github.ref_name }} | sed -e 's/^v\(.*\)/\1/')" >> $GITHUB_ENV
      - name: Compile Binary and Create Tarball
        run: ./ci/scripts/create_binary_package.sh
        env:
          TARGET: ${{ matrix.target }}-${{ matrix.arch }}
      - name: Publish Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hyperledger-fabric-${{ matrix.target }}-${{ matrix.arch }}-${{ env.RELEASE }}.tar.gz
          path: release/${{ matrix.target }}-${{ matrix.arch }}/hyperledger-fabric-${{ matrix.target }}-${{ matrix.arch }}-${{ env.RELEASE }}.tar.gz
  build-and-push-docker-images:
    name: Build and Push Fabric Docker Images
    runs-on: ubuntu-20.04
    steps:
      - name: Run APT Clean
        run: sudo apt clean
      - name: Run Apt Update
        run: sudo apt update
      - name: Install Dependencies
        run: sudo apt install -y gcc haveged libtool make
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VER }}
      - name: Checkout Fabric Code
        uses: actions/checkout@v3
      - name: Set three digit RELEASE (strip leading v)
        run: echo "RELEASE=$(echo ${{ github.ref_name }} | sed -e 's/^v\(.*\)/\1/')" >> $GITHUB_ENV
      - name: Set TWO_DIGIT_RELEASE (strip leading v and use major.minor)
        run: echo "TWO_DIGIT_RELEASE=$(echo ${{ github.ref_name }} | sed -e 's/^v\(.*\)/\1/' | cut -d '.' -f 1,2)" >> $GITHUB_ENV
      - name: Publish Docker Images
        run: ./ci/scripts/publish_docker.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  create-release:
    name: Create GitHub Release
    needs: [ build-binaries , build-and-push-docker-images]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout Fabric Code
        uses: actions/checkout@v3
      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v3
      - name: Release Fabric Version
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz/*.tar.gz"
          bodyFile: release_notes/${{ github.ref_name }}.md
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
