# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: "Security vulnerability scan"

on:
  workflow_dispatch:
  schedule:
    - cron: "50 1 * * *"

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ref:
          - main
          - release-2.5
          - release-2.4
          - release-2.2
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.ref }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.3
      - name: Scan
        run: make scan
